#!/bin/sh

# Include the wrappers utility script
. /usr/lib/java-wrappers/java-wrappers.sh

find_java_runtime java6

SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
run_jar /usr/share/sbt/sbt-launch-*.jar -Dsbt.boot.properties=/usr/share/sbt/sbt.boot.properties "$@"

